- hosts: 119.3.50.108
  tasks:
    - name: copy conf file
      copy: src=template/jenkins.conf  dest=/etc/nginx/conf/conf.d
    - name: check conf
      shell: /usr/sbin/nginx -t 
      register: nginx_conf_result
    - name: reload nginx conf
      shell: /usr/sbin/nginx -s reload
      when: nginx_conf_result is succeeded
